/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElCard: typeof import('element-plus/es')['ElCard']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    SecurityLink: typeof import('./src/components/SecurityLinks/SecurityLink.vue')['default']
    SecurityLinks: typeof import('./src/components/SecurityLinks/SecurityLinks.vue')['default']
    SecurityLinksMain: typeof import('./src/components/SecurityLinks/SecurityLinksMain.vue')['default']
  }
}
